function [ Ext ] = Extension_Input(  )
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here

    d = dialog('Position',[600 500 500 300],'Name','Select Extension Type');
    Ext = '\*dm3';
    
    txt1 = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[210 50 80 140],...
               'String', 'Select Extension',...
               'HorizontalAlignment', 'left');

    popup2 = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[210 140 100 25],...
           'String',{'dm3'; 'dm4'; 'tif'; 'tiff'; 'jpg'; 'png'},...
           'Callback',@popup_callback1);
   
    btn = uicontrol('Parent',d,...
               'Position',[220 100 70 25],...
               'String','Select',...
               'Callback','delete(gcf)');

uiwait(d);

      function popup_callback1(popup2, callbackdata)
          idx2 = get(popup2, 'Value');
          popup_items2 = get(popup2, 'String');
          Ext = strcat('\*', char(popup_items2(idx2,:)));
       end
           
end

