function [ Unit ] = Unit_Input(  )
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here

    d = dialog('Position',[600 500 500 300],'Name','Select Units');
    Unit = 'ns';
    
    txt1 = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[210 50 80 140],...
               'String', 'Select Units',...
               'HorizontalAlignment', 'left');

    popup2 = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[210 140 100 25],...
           'String',{'ns'; 'ps'; 'fs'},...
           'Callback',@popup_callback1);
   
    btn = uicontrol('Parent',d,...
               'Position',[220 100 70 25],...
               'String','Select',...
               'Callback','delete(gcf)');

uiwait(d);

      function popup_callback1(popup2, callbackdata)
          idx2 = get(popup2, 'Value');
          popup_items2 = get(popup2, 'String');
          Unit = char(popup_items2(idx2,:));
       end
           
end
